theme: jekyll-theme-slate
title: Setupesc
description: Make your computer work for you again
other:
  alexesc: https://alex-esc.github.io/
  home: https://alex-esc.github.io/getsetupesc/
  orgrepo: https://github.com/alex-esc/setupesc
  download: https://github.com/alex-esc/setupesc/archive/master.zip
  learnmore: https://alex-esc.github.io/getsetupesc/documentation.html
  getupdates: https://alex-esc.github.io/getsetupesc/update.html
